### ISSUE TITLE
try to use on first time and get TypeError

### ISSUE THREAD

**Issue by omer72** [mcfly-io/generator-mcfly#189]
events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.

**Comment by thaiat** [comment]
hi @omer72 
you have to give a little more details on what exactly you are doing when this happens, otherwise i can't really figure it out.
the more detail you give on your config, steps you followed for installation, etc... the easier it will be to solve your issue

**Comment by thaiat** [comment]
closing this due to inactivity, feel free to reopen with more details

**Comment by jercoh** [comment]
Got the same error here. Here are the logs:
```
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/Users/Jeremie/.node/bin/npm" "install" "chalk@1.0.0" "gulp@3.9.0" "gulp-help@1.6.0" "gulp-if@1.2.5" "gulp-load-plugins@1.0.0-rc.1" "gulp-mux" "gulp-util@3.0.5" "lodash@3.9.3" "require-dir@0.3.0" "run-sequence@1.1.0" "strip-json-comments@1.0.2" "growly@1.2.0" "gulp-eslint@0.13.2" "gulp-jshint@1.11.0" "gulp-jscs@1.6.0" "gulp-plumber@1.0.1" "jshint-stylish@2.0.0" "map-stream@0.0.5" "stream-combiner@0.2.2" "browser-sync@2.7.7" "brfs@1.4.0" "browserify@10.2.3" "browserify-istanbul@0.2.1" "browserify-shim@3.8.8" "bundle-collapser@1.2.0" "babelify@6.1.2" "cssify@0.7.0" "deamdify@0.1.1" "del@1.2.0" "envify@3.4.0" "exorcist@0.4.0" "html2js-browserify@1.0.0" "jadeify@4.3.0" "mkdirp@0.5.1" "uglifyify@3.0.1" "vinyl-buffer@1.0.0" "vinyl-source-stream@1.1.0" "vinyl-transform@1.0.0" "watchify@3.2.2" "github@0.2.4" "github-username@2.0.0" "gulp-bump@0.3.1" "gulp-git@1.2.4" "gulp-tap@0.1.3" "inquirer@0.8.5" "node-jsxml@0.6.0" "q@1.4.1" "yargs@3.10.0" "conventional-changelog@0.0.17" "gulp-exec@2.1.1" "gulp-concat@2.5.2" "streamqueue@1.1.0" "chai@3.0.0" "gulp-mocha@2.1.1" "gulp-istanbul@0.10.0" "gulp-protractor@0.0.12" "gulp-karma@0.0.4" "jasmine-reporters@2.0.6" "jasmine-spec-reporter@2.2.3" "karma@0.12.36" "karma-browserify@4.2.1" "karma-coverage@0.4.1" "karma-growl-reporter@0.1.1" "karma-jasmine@0.3.5" "karma-mocha-reporter@1.0.2" "karma-phantomjs-launcher@0.2.0" "mocha@2.2.5" "mocha-lcov-reporter@0.0.2" "protractor@2.1.0" "protractor-html-screenshot-reporter@0.0.19" "sinon@1.15.1" "event-stream@3.3.1" "gulp-sass@2.0.1" "gulp-less@3.0.3" "gulp-sourcemaps@1.5.2" "gulp-autoprefixer@2.3.1" "gulp-minify-css@1.1.6" "gulp-order@1.1.1" "gulp-rename@1.2.2" "gulp-size@1.2.1" "--save-dev" "--save-exact"
npm ERR! node v0.10.33
npm ERR! npm  v2.10.0

npm ERR! version not found: gulp-sass@2.0.1
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Jeremie/javascript/mc-fly-test/npm-debug.log

events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at emit (events.js:74:15)
    at done (/Users/Jeremie/.node/lib/node_modules/generator-sublime/node_modules/yeoman-generator/lib/base.js:383:23)
    at null.<anonymous> (/Users/Jeremie/.node/lib/node_modules/generator-sublime/node_modules/yeoman-generator/lib/actions/install.js:44:7)
    at ChildProcess.emit (events.js:117:20)
    at Process.ChildProcess._handle.onexit (child_process.js:810:12)
```

**Comment by thaiat** [comment]
looks like you are using node 0.10.33. try upgrading to 0.12.4 and rerun the generator

**Comment by jercoh** [comment]
Same error:
```
npm ERR! node v0.12.5
npm ERR! npm  v2.10.0

npm ERR! version not found: gulp-sass@2.0.1
```

**Comment by thaiat** [comment]
can you try `npm install --save-dev gulp-sass`

**Comment by jercoh** [comment]
This command worked. 
I also upgraded `generator-sublime` and `generator-mcfly` to the last versions. I tried to run `yo mcfly <myApp>` but it failed again. Same error...

**Comment by thaiat** [comment]
now try `npm install --save-dev gulp-sass@2.0.1`

**Comment by jercoh** [comment]
Failed...

**Comment by thaiat** [comment]
good !!! so that's the issue
I ll publish a workaround and a fix later on

**Comment by jercoh** [comment]
Thank you @thaiat!

**Comment by thaiat** [comment]
try this workaround:    
in the project where the install failed you'll find a file named `.gulps-package.json`

This file is generated before the generator tries to do an `npm install` in case it fails

so you can do the following:

- copy the content of the `devDependencies` section of this file in the `devDependencies` of `package.json`
- modify the version of gulp-sass to be 2.0.2
- save the resulting `package.json`
- run `npm install`
this should put you in the same state as if the generated succeeded

let me know how it went

**Comment by jercoh** [comment]
This workaround worked thanks. 
Is the dependencies installation the last step of the init step?

**Comment by thaiat** [comment]
@jercoh yep

**Comment by jskrzypek** [comment]
Looks like they de-listed the 2.0.1 release of `gulp-sass`. @alferov has a PR on https://gtihub.com/mcfly-io/generator-sublime which fixes it.
