### ISSUE TITLE
Error when trying to generate a project.

### ISSUE THREAD

**Issue by sebad78** [mcfly-io/generator-mcfly#301]
yo mcfly
python is installed, continuing...

     _-----_
    |       |    .--------------------------.
    |--(o)--|    |  Welcome to the amazing  |
   `---------´   |     mcfly generator!     |
    ( _´U`_ )    '--------------------------'
    /___A___\    
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

[?] Do you want your filenames in camelCase or snake-case? snake-case
[?] Would you like to use Johnpappa style filename suffixes? ("homeCtrl.controller.js" vs "homeCtrl.js") No/N) 
[?] How would you like to name the client folder? client
[?] Would you like to include ionic framework? No

/usr/local/lib/node_modules/yo/node_modules/yeoman-generator/node_modules/inquirer/lib/utils/utils.js:34
  var isValid = func.apply({
                     ^
TypeError: undefined is not a function
    at Object.utils.runAsync (/usr/local/lib/node_modules/yo/node_modules/yeoman-generator/node_modules/inquirer/lib/utils/utils.js:34:22)
    at PromptUI.onEachPrompt (/usr/local/lib/node_modules/yo/node_modules/yeoman-generator/node_modules/inquirer/lib/ui/prompt.js:85:9)
    at /usr/local/lib/node_modules/yo/node_modules/yeoman-generator/node_modules/inquirer/node_modules/async/lib/async.js:249:17
    at iterate (/usr/local/lib/node_modules/yo/node_modules/yeoman-generator/node_modules/inquirer/node_modules/async/lib/async.js:149:13)
    at /usr/local/lib/node_modules/yo/node_modules/yeoman-generator/node_modules/inquirer/node_modules/async/lib/async.js:160:25
    at /usr/local/lib/node_modules/yo/node_modules/yeoman-generator/node_modules/inquirer/node_modules/async/lib/async.js:251:21
    at PromptUI.<anonymous> (/usr/local/lib/node_modules/yo/node_modules/yeoman-generator/node_modules/inquirer/lib/ui/prompt.js:66:5)
    at Object.utils.runAsync (/usr/local/lib/node_modules/yo/node_modules/yeoman-generator/node_modules/inquirer/lib/utils/utils.js:42:5)
    at Prompt.filter (/usr/local/lib/node_modules/yo/node_modules/yeoman-generator/node_modules/inquirer/lib/prompts/base.js:149:9)
    at Prompt.done (/usr/local/lib/node_modules/yo/node_modules/yeoman-generator/node_modules/inquirer/lib/prompts/base.js:71:10)
    at Prompt.<anonymous> (/usr/local/lib/node_modules/yo/node_modules/yeoman-generator/node_modules/inquirer/lib/prompts/confirm.js:97:10)
    at Object.utils.runAsync (/usr/local/lib/node_modules/yo/node_modules/yeoman-generator/node_modules/inquirer/lib/utils/utils.js:42:5)
    at Prompt.filter (/usr/local/lib/node_modules/yo/node_modules/yeoman-generator/node_modules/inquirer/lib/prompts/base.js:149:9)
    at Prompt.onSubmit (/usr/local/lib/node_modules/yo/node_modules/yeoman-generator/node_modules/inquirer/lib/prompts/confirm.js:93:8)
    at Interface.g (events.js:199:16)
    at Interface.emit (events.js:107:17)

**Comment by jskrzypek** [comment]
1.) Why do you think python being installed is related?

2.) What version of node/npm are you running and what OS?
Also if you don't mind giving us the versions of your top-level global npm packages that might help in diagnosing. Run this:
```
npm ls -g --depth=0
```

**Comment by thaiat** [comment]
can you retry with latest version
let me know if you need to reopen
